spring.application.name=finance-tracker

# H2 Database
spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Server
server.port=8080

# TraceHub SDK
tracehub.api-key=th_066f481abae675bdba7c80fee4dbf647358a6d11839b81aad1ef3a8d82b06134
tracehub.service=finance-tracker
tracehub.environment=development
